### ISSUE TITLE
context is not defined

### ISSUE THREAD

**Issue by spencersmb** [wp-graphql/wp-graphql#1141]
Tried to publish a new static site build from Gatsby this morning with minor CSS changes and this error appeared. 2 days ago I was able to publish just fine. I've seen others with the same error on slack. I can't even query basic posts anymore under wpgraphql.

Running:
"gatsby-source-graphql": "^2.1.33",
WP GraphQL v.6.0

Here is the error output:
```
{
  "errors": [
    {
      "message": "context is not defined",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "wpgraphql",
        "posts"
      ],
      "stack": [
        "ReferenceError: context is not defined",
        "    at buildDelegationTransforms (/Users/spencerbigum/Documents/github/etShop-gatsby/node_modules/graphql-tools-fork/dist/stitching/delegateToSchema.js:48:98)",
        "    at delegateRequest (/Users/spencerbigum/Documents/github/etShop-gatsby/node_modules/graphql-tools-fork/dist/stitching/delegateToSchema.js:75:32)",
        "    at Object.delegateToSchema [as default] (/Users/spencerbigum/Documents/github/etShop-gatsby/node_modules/graphql-tools-fork/dist/stitching/delegateToSchema.js:40:12)",
        "    at /Users/spencerbigum/Documents/github/etShop-gatsby/node_modules/graphql-tools-fork/dist/stitching/resolvers.js:57:86",
        "    at resolveFieldValueOrError (/Users/spencerbigum/Documents/github/etShop-gatsby/node_modules/graphql/execution/execute.js:467:18)",
        "    at resolveField (/Users/spencerbigum/Documents/github/etShop-gatsby/node_modules/graphql/execution/execute.js:434:16)",
        "    at executeFields (/Users/spencerbigum/Documents/github/etShop-gatsby/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (/Users/spencerbigum/Documents/github/etShop-gatsby/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (/Users/spencerbigum/Documents/github/etShop-gatsby/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeValue (/Users/spencerbigum/Documents/github/etShop-gatsby/node_modules/graphql/execution/execute.js:591:12)",
        "    at completeValue (/Users/spencerbigum/Documents/github/etShop-gatsby/node_modules/graphql/execution/execute.js:557:21)",
        "    at completeValueCatchingError (/Users/spencerbigum/Documents/github/etShop-gatsby/node_modules/graphql/execution/execute.js:495:19)",
        "    at resolveField (/Users/spencerbigum/Documents/github/etShop-gatsby/node_modules/graphql/execution/execute.js:435:10)",
        "    at executeFields (/Users/spencerbigum/Documents/github/etShop-gatsby/node_modules/graphql/execution/execute.js:275:18)",
        "    at executeOperation (/Users/spencerbigum/Documents/github/etShop-gatsby/node_modules/graphql/execution/execute.js:219:122)",
        "    at executeImpl (/Users/spencerbigum/Documents/github/etShop-gatsby/node_modules/graphql/execution/execute.js:104:14)",
        "    at execute (/Users/spencerbigum/Documents/github/etShop-gatsby/node_modules/graphql/execution/execute.js:64:35)",
        "    at getGraphQLParams.then.then.optionsData (/Users/spencerbigum/Documents/github/etShop-gatsby/node_modules/express-graphql/index.js:152:16)",
        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
      ]
    }
  ],
  "data": {
    "wpgraphql": {
      "posts": null
    }
  }
}
```

**Comment by spencersmb** [comment]
Latest update: I downgraded to 2.1.25 and was able to complete a build on Netlify.

**Comment by jerome281** [comment]
Yep getting the same issue using `gatsby-source-graphql": "2.1.33"` with WP GraphQL v.6.0

**Comment by jasonbahl** [comment]
@spencersmb @jerome281 I was away from the computer for the past 11 days. I was catching up on Slack this morning, and it looks like ya'll resolved this by switching to a specific version of `gatsby-source-graphql`. 

I believe I can safely close this issue as it seems to be an issue with that source plugin and not WPGraphQL. 

If there's evidence of something wrong on the WPGraphQL side that can be addressed, let me know and we can re-open or open another issue. Thanks!
