### ISSUE TITLE
Cannot query for featured image

### ISSUE THREAD

**Issue by nerdess** [wp-graphql/wp-graphql#1480]
The plugin works perfect so far but now I am failing at the simple task of grabbing the featured image.

Here is my query that I created using GraphiQL:

```query MyQuery {
  wpgraphql {
    pages {
      edges {
        node {
          id
          title
          featuredImage {
            id
          } 
        }
      }
    }
  }
}
```

Here is the error message I get:

```
{
  "errors": [
    {
      "message": "Cannot query field \"id\" on type \"WPGraphQL_NodeWithFeaturedImageToMediaItemConnectionEdge\".",
      "locations": [
        {
          "line": 9,
          "column": 13
        }
      ],
      "stack": [
        "GraphQLError: Cannot query field \"id\" on type \"WPGraphQL_NodeWithFeaturedImageToMediaItemConnectionEdge\".",
        "    at Object.Field (/Users/Sissi/Sites/xyz/development/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:53:31)",
        "    at Object.enter (/Users/Sissi/Sites/xyz/development/node_modules/graphql/language/visitor.js:324:29)",
        "    at Object.enter (/Users/Sissi/Sites/xyz/development/node_modules/graphql/language/visitor.js:375:25)",
        "    at visit (/Users/Sissi/Sites/xyz/development/node_modules/graphql/language/visitor.js:242:26)",
        "    at validate (/Users/Sissi/Sites/xyz/development/node_modules/graphql/validation/validate.js:73:24)",
        "    at /Users/Sissi/Sites/xyz/development/node_modules/express-graphql/index.js:121:32",
        "    at runMicrotasks (<anonymous>)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
      ]
    }
  ]
}
```

I am still at the beginning of learning GraphQL and right now I am stuck....

**Comment by jasonbahl** [comment]
@nerdess In v0.10.0 some changes were made to the Schema to reflect 1-to-1 connections better. 

So now, instead of: 

```graphql

featuredImage {
  id
} 

```

The query would be: 

```graphql
featuredImage {
  node { // <-- Note this change
    id
  }
} 
```
