### ISSUE TITLE
Bump composer dependencies for PHP 8 compatibility

### ISSUE THREAD

**Issue by kellenmace** [wp-graphql/wp-graphql#1755]
It looks like we'll need to bump a few composer dependencies in order to be compatible with PHP 8. Cloning this repo from GitHub into a PHP 8 WordPress project, then running `composer install` currently results in this:

```
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - ivome/graphql-relay-php is locked to version v0.5.0 and an update of this package was not requested.
    - ivome/graphql-relay-php v0.5.0 requires php >=5.4,<8.0-DEV -> your php version (8.0.0) does not satisfy that requirement.
  Problem 2
    - wp-cli/scaffold-command is locked to version v2.0.8 and an update of this package was not requested.
    - wp-cli/scaffold-command v2.0.8 requires php ^5.4 || ^7.0 -> your php version (8.0.0) does not satisfy that requirement.
  Problem 3
    - wp-cli/wp-cli is locked to version v2.4.1 and an update of this package was not requested.
    - wp-cli/wp-cli v2.4.1 requires php ^5.4 || ^7.0 -> your php version (8.0.0) does not satisfy that requirement.
  Problem 4
    - wp-cli/scaffold-command v2.0.8 requires php ^5.4 || ^7.0 -> your php version (8.0.0) does not satisfy that requirement.
    - wp-cli/wp-cli-bundle v2.4.0 requires wp-cli/scaffold-command ^2 -> satisfiable by wp-cli/scaffold-command[v2.0.8].
    - wp-cli/wp-cli-bundle is locked to version v2.4.0 and an update of this package was not requested.
```

**Comment by jasonbahl** [comment]
so, the GraphQL PHP dependency explicitly declares support for PHP versions below 8.0. 

WPGraphQL hardly uses this extension, so I think it might be good to remove this dependency altogether. 

I think for backward compatibility we can bring in some of the functions under the same namespace, such as `GraphQLRelay\Relay::toGlobalId()` and `GraphQLRelay\Relay::fromGlobalId()`, while fully deprecating the vendor dependency, and over time even deprecating these functions for more native-to-wpgraphql functions.

**Comment by jasonbahl** [comment]
Ok, on further inspection, this is deeper than just the Relay dependency. 

I forked the dependency and updated the composer.json to show support for PHP 8. (https://github.com/jasonbahl/graphql-relay-php/blob/master/composer.json) 

Then updated WPGraphQL composer to install the dependency from my fork: 

```json
  "repositories": [
    {
      "type":"package",
      "package": {
        "name": "jasonbahl/graphql-relay-php",
        "version":"master",
        "source": {
          "url": "https://github.com/jasonbahl/graphql-relay-php.git",
          "type": "git",
          "reference":"master"
        }
      }
    }
  ],
  "require": {
    "php": ">=7.1.0|^8.0",
    "webonyx/graphql-php": "14.5.1",
    "jasonbahl/graphql-relay-php": "dev-master"
  },
```

But then running the `composer install-test-env` runs into issues with WP CLI not being able to properly execute and install the environment: 

```bash
+ wp config create --dbname=wptests --dbuser=root --dbpass=password --dbhost=127.0.0.1 --skip-check --force=true
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/WP_CLI/DocParser.php:75
Stack trace:
#0 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/WP_CLI/DocParser.php(75): implode(Array, '\n')
#1 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CompositeCommand.php(32): WP_CLI\DocParser->get_longdesc()
#2 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(117): WP_CLI\Dispatcher\CompositeCommand->__construct(Object(WP_CLI\Dispatcher\RootCommand), 'package', Object(WP_CLI\DocParser))
#3 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(49): WP_CLI\Dispatcher\CommandFactory::create_composite_command(Object(WP_CLI\Dispatcher\RootCommand), 'package', 'Package_Command')
#4 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/class-wp-cli.php(516): WP_CLI\Dispatcher\CommandFactory::create('package', 'Package_Command', Object(WP_CLI\Dispatcher\RootCommand))
#5 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/package-command/package-command.php(11): WP_CLI::add_command('package', 'Package_Command')
#6 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/composer/autoload_real.php(69): require('/Users/jason.ba...')
#7 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/composer/autoload_real.php(59): composerRequire097cafea876bd8290ef66d6ac5b79d4b('ba366f96f4fddbd...', '/Users/jason.ba...')
#8 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/autoload.php(7): ComposerAutoloaderInit097cafea876bd8290ef66d6ac5b79d4b::getLoader()
#9 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/AutoloaderStep.php(49): require('/Users/jason.ba...')
#10 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\AutoloaderStep->process(Object(WP_CLI\Bootstrap\BootstrapState))
#11 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/wp-cli.php(25): WP_CLI\bootstrap()
#12 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/boot-fs.php(17): require_once('/Users/jason.ba...')
#13 {main}
  thrown in /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/WP_CLI/DocParser.php on line 75

Fatal error: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/WP_CLI/DocParser.php:75
Stack trace:
#0 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/WP_CLI/DocParser.php(75): implode(Array, '\n')
#1 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CompositeCommand.php(32): WP_CLI\DocParser->get_longdesc()
#2 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(117): WP_CLI\Dispatcher\CompositeCommand->__construct(Object(WP_CLI\Dispatcher\RootCommand), 'package', Object(WP_CLI\DocParser))
#3 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(49): WP_CLI\Dispatcher\CommandFactory::create_composite_command(Object(WP_CLI\Dispatcher\RootCommand), 'package', 'Package_Command')
#4 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/class-wp-cli.php(516): WP_CLI\Dispatcher\CommandFactory::create('package', 'Package_Command', Object(WP_CLI\Dispatcher\RootCommand))
#5 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/package-command/package-command.php(11): WP_CLI::add_command('package', 'Package_Command')
#6 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/composer/autoload_real.php(69): require('/Users/jason.ba...')
#7 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/composer/autoload_real.php(59): composerRequire097cafea876bd8290ef66d6ac5b79d4b('ba366f96f4fddbd...', '/Users/jason.ba...')
#8 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/autoload.php(7): ComposerAutoloaderInit097cafea876bd8290ef66d6ac5b79d4b::getLoader()
#9 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/AutoloaderStep.php(49): require('/Users/jason.ba...')
#10 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\AutoloaderStep->process(Object(WP_CLI\Bootstrap\BootstrapState))
#11 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/wp-cli.php(25): WP_CLI\bootstrap()
#12 /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/boot-fs.php(17): require_once('/Users/jason.ba...')
#13 {main}
  thrown in /Users/jason.bahl/Sites/libs/wp-graphql/vendor/wp-cli/wp-cli/php/WP_CLI/DocParser.php on line 75
```

**Comment by jasonbahl** [comment]
Looks related to this: https://github.com/wp-cli/wp-cli/issues/5482#issuecomment-749849908

**Comment by jasonbahl** [comment]
Marked this as blocked per the previous issue linked in the wp-cli repo

**Comment by Lornz-** [comment]
Hi,

I recently bumped to that same issue when trying to install WP Graphql plugin via composer :
```
Using version ^1.3 for wp-graphql/wp-graphql
./composer.json has been updated
Running composer update wp-graphql/wp-graphql
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - wp-graphql/wp-graphql[v1.3.0, ..., v1.3.8] require ivome/graphql-relay-php 0.5.0 -> satisfiable by ivome/graphql-relay-php[v0.5.0].
    - ivome/graphql-relay-php v0.5.0 requires php >=5.4,<8.0-DEV -> your php version (8.0.3) does not satisfy that requirement.
    - Root composer.json requires wp-graphql/wp-graphql ^1.3 -> satisfiable by wp-graphql/wp-graphql[v1.3.0, ..., v1.3.8].


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

Anything new on that issue?

**Comment by Lornz-** [comment]
**graphql-relay-php** now support PHP 8.0:  [ivome/graphql-relay-php#20](https://github.com/ivome/graphql-relay-php/issues/20). Would it possible to bump that dependency to the latest version v0.6.0?

**Comment by Lornz-** [comment]
For those who are interested, I've found a workaround to make it work, at least temporally. Basically, I faked the PHP version by forcing the one that satisfy all my required dependencies but still using the up-to-date version of PHP on my server.
```json
"config": {
  "platform":{
    "php":"7.3"
  },
}
```

**Comment by jasonbahl** [comment]
@Lornz- @kellenmace (any anoyone else following) WPGraphQL is now working with PHP 8 as of v1.5.1 (https://github.com/wp-graphql/wp-graphql/releases/tag/v1.5.1) 🎉

**Comment by Lornz-** [comment]
Excellent! Thanks @jasonbahl for the update.
