### ISSUE TITLE
Uncaught TypeError: Argument 2 passed to GraphQL\Utils\Value::coerceValue()

### ISSUE THREAD

**Issue by lance-anderson** [wp-graphql/wp-graphql#1765]
Using version 1.2.5 I get an Uncaught TypeError and it's not clear what I am doing wrong. Plugin is great; been using it for months now for queries but now writing a few mutations and ran into this error:

```
[09-Mar-2021 20:25:03 UTC] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to GraphQL\Utils\Value::coerceValue() must implement interface GraphQL\Type\Definition\InputType, instance of WPGraphQL\Type\WPObjectType given, called in ~/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/Value.php on line 167 and defined in ~/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/Value.php:42
Stack trace:
#0 ~/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/Value.php(167): GraphQL\Utils\Value::coerceValue(Array, Object(WPGraphQL\Type\WPObjectType), Object(GraphQL\Language\AST\VariableDefinitionNode), Array)
#1 ~/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/Value.php(124): GraphQL\Utils\Value::coerceValue(Array, Object(WPGraphQL\Type\WPInputObje in ~/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/Value.php on line 42
```

I am trying to use the `list_of` option to specify a list of `NavLabelValue` objects. I use:
`'type' => 'NavLabelValue',`
It works as expected but I can only pass a single NavLabelValue into the mutation whereas I would like to pass a list of NavLabelValues into the mutation so I tried this but it throws the above error.
`'type' => [ 'list_of' => 'NavLabelValue' ],`

#### Code snippet for context

```
  register_graphql_input_type( 'NavLabelValue', [
    'description' => __( 'An object containing the multilingual strings for a nav labels.', get_graphql_domain()),
    'fields' => [
      'value' => [
        'type' => 'MultilingualString', 
        'description' => __( 'Multilingual strings from the CMS', get_graphql_domain()),
      ],
    ],
  ] );

  register_graphql_input_type( 'NavLabels', [
    'description' => __( 'An object containing all multilingual nav labels from the CMS.', get_graphql_domain()),
    'fields' => [
      'labels' => [
        'type' => [ 'list_of' => 'NavLabelValue' ],
        'description' => __( 'List of navigation labels', get_graphql_domain()),
      ],
    ],
  ] );
```

**Comment by lance-anderson** [comment]
@jasonbahl or anyone else- can you confirm if this option is supported? Can an `InputType` be registered to use a list for another `InputType`?

Everything works as expected if I change the `register_graphql_input_type` definition from my custom `NavLabelValue` InputType to use a list of Strings instead.

**works:**
`'type' => [ 'list_of' => 'String' ],`

**doesn't work:**
`'type' => [ 'list_of' => 'NavLabelValue' ],`

**Comment by lance-anderson** [comment]
Looks like @esamattis encountered a similar issue, albeit with a different error message, while trying to accomplish the same thing: https://spectrum.chat/wpgraphql/general/how-to-register-complex-input-fields~d081cde3-fe88-472f-b91c-f33b01d9ea87

@esamattis- Any chance you found a solution?

**Comment by lance-anderson** [comment]
Forgive the spam. This was my mistake. 🤦🏼‍♂️

For anyone else who happens to encounter this error and gets stuck:

In the code snippet above, `NavLabelValue` is using type `MultilingualString` which is an "ObjectType" instead of an "InputType" — as the PHP error noted. In my use case, I just needed to define a `MultilingualInput` "InputType" and everything worked as expected.
