### ISSUE TITLE
Multisite Network Error: Unexpected token ﻿ in JSON at position 0

### ISSUE THREAD

**Issue by KhadijaMahanga** [wp-graphql/wp-graphql#2017]
I am getting this error from my multi-site wordpress. Can anyone assist. However I can see the data is being returned and statusCode 200.

Note; the unexpected token here is an invisible character.

WPGraphQL  Version 1.5.2 
 
```
ApolloError: Unexpected token ﻿ in JSON at position 0
    at new ApolloError (/../node_modules/@apollo/client/errors/errors.cjs.js:31:28)
    at /.../node_modules/@apollo/client/core/core.cjs.js:1493:19
    at both (/.../node_modules/@apollo/client/utilities/utilities.cjs.js:963:53)
    at /..../node_modules/@apollo/client/utilities/utilities.cjs.js:956:72
    at new Promise (<anonymous>)
    at Object.then (/.../node_modules/@apollo/client/utilities/utilities.cjs.js:956:24)
    at Object.error (/.../node_modules/@apollo/client/utilities/utilities.cjs.js:964:49)
    at notifySubscription (/.../node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/..../node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/..../node_modules/zen-observable/lib/Observable.js:240:7) {
  graphQLErrors: [],
  networkError: SyntaxError [ServerParseError]: Unexpected token ﻿ in JSON at position 0
      at JSON.parse (<anonymous>)
      at /..../node_modules/@apollo/client/link/http/http.cjs.js:18:25
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    response: Response {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    },
    statusCode: 200,
    bodyText: '﻿{"data":{"homepageSettings":{"frontPage":{"seo":{"breadcrumbs":[{"text":"Home","url":"\\/","__typename":"SEOPostTypeBreadcrumbs"}],"canonical":...
```

**Comment by JMartinCollins** [comment]
need to call .json() on your data?
