### ISSUE TITLE
Ticking "Enable GraphQL Tracing" causes a critical site error in version 1.8.3

### ISSUE THREAD

**Issue by evangelinepapanicola** [wp-graphql/wp-graphql#2420]
A few of our sites that had the GraphQL Tracing option enabled updated automatically to WPGraphQL 1.8.3 last night and went down. It causes a critical WP error at the /graphql endpoint, and upon further digging produces this error:

```
AH01071: Got error 'PHP message: PHP Fatal error: Uncaught TypeError: Argument 3 passed to
WPGraphQL\\Utils\\Tracing::add_tracing_to_response_extensions() must be of the type string, null given, called in
/var/www/vhosts/redacted.com/httpdocs/wp-includes/class-wp-hook.php on line 309 and defined in
/var/www/vhosts/redacted.com/httpdocs/wp-content/plugins/wp-graphql/src/Utils/Tracing.php:272\nStack trace:\n#0
/var/www/vhosts/redacted.com/httpdocs/wp-includes/class-wp-hook.php(309): WPGraphQL\\Utils\\Tracing
>add_tracing_to_response_extensions()\n#1 /var/www/vhosts/redacted.com/httpdocs/wp-includes/plugin.php(191): WP_Hook
>apply_filters()\n#2 /var/www/vhosts/redacted.com/httpdocs/wp-content/plugins/wp-graphql/src/Request.php(539):
apply_filters()\n#3 /var/www/vhosts/redacted.com/httpdocs/wp-content/plugins/wp-graphql/src/Request.php(423):
WPGraphQL\\Request->after_execute_actions()\n#4 /var/www/vhosts/redacted.com/httpdocs/wp-content/plugins/wp
graphql/src/Request.php(682): WPGraphQL\\Request->after_execute()\n#5 /var/www/vhosts/p...'
```

**Comment by justlevine** [comment]
👀 https://github.com/wp-graphql/wp-graphql/blob/16b159fe40ebdc12e1b7ce968b27ec0a9d1943e2/src/Request.php#L477

**Comment by jasonbahl** [comment]
I've reproduced and have a PR coming
