### ISSUE TITLE
1.13.0 - Gatsby - Error: Cannot destructure property 'fields' of 'nodesType' as it is undefined

### ISSUE THREAD

**Issue by fly-oinotna** [wp-graphql/wp-graphql#2634]
### Description

Updated a couple of hours ago to 1.13.0 and I wasn't able to start my Gatsby app, not even in develop mode.

Tried to disable all plugins and the error still remained. Rolled back to 1.12.3, and everything works fine again. After re-activating all other plugins everything works fine

### Steps to reproduce

"gatsby develop"

### Additional context

**Detailed error:**

TypeError: Cannot destructure property 'fields' of 'nodesType' as it is undefined.
    at generateNodeQueriesFromIngestibleFields (/xxx/gatsbyapp/node_modules/gatsby-source-wordpress/src/steps/ingest-remote-schema/build-queries-from-introspection/generate-queries-from-ingestable-types.js:155:13)
    at buildNodeQueries
(/xxx/gatsbyapp/node_modules/gatsby-source-wordpress/src/steps/ingest-remote-schema/build-queries-from-introspection/build-node-queries.js:25:25)
    at runSteps (/xxx/gatsbyapp/node_modules/gatsby-source-wordpress/src/utils/run-steps.ts:41:9)
    at runSteps (/xxx/gatsbyapp/node_modules/gatsby-source-wordpress/src/utils/run-steps.ts:43:9)
    at ingestRemoteSchema (/xxx/gatsbyapp/node_modules/gatsby-source-wordpress/src/steps/ingest-remote-schema/index.js:49:5)
    at runSteps (/xxx/gatsbyapp/node_modules/gatsby-source-wordpress/src/utils/run-steps.ts:41:9)
    at runAPI (/xxx/gatsbyapp/node_modules/gatsby/src/utils/api-runner-node.js:487:16)

### WPGraphQL Version

1.13.0

### WordPress Version

6.1.1

### PHP Version

8.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
I've talked with @TylerBarnes the maintainer of Gatsby Source WordPress. 

It seems like there's some conflicts with Types. v1.13.0 of WPGraphQL introduced a Connection Interface, implemented by all Connections. 

Gatsby also has a Connection type, so this was causing some conflicts. 

We're looking into resolving this from both sides. 

Hope to have something soon

**Comment by fly-oinotna** [comment]
Thank you @jasonbahl, I'll wait for news before updating again!

**Comment by TylerBarnes** [comment]
Hi @fly-oinotna sorry for the trouble here, I'm very close to having a solution. You can follow along here https://github.com/gatsbyjs/gatsby/issues/37114
