### ISSUE TITLE
Performance issue when loading text domains.

### ISSUE THREAD

**Issue by creative-andrew** [wp-graphql/wp-graphql#2721]
### Description

Every single GraphQL field has a semantic description, which looks like is getting translated on every single query even though they don't really need to be.

This is creating massive calls to the `__()` and `load_textdomain()` functions.

Additionally, the whole schema seems to be created and queried during each request, generating a massive object that is impossible to cache.  

### Steps to reproduce

1. This should be tested in a similar way to this [previously reported issue](https://github.com/wp-graphql/wp-graphql/issues/1873), namely by adding 30 CPT and terms. 
2. Perform some queries in English as the default language. Make sure your query includes a fair number of nodes and fields. 
3. Change to a different language and perform the same query.

### Blocking `wp-graphl` text domain on demand.

If you prevent loading the `$mofile` for the `wp-graphql` text domain you would notice the speed bump. As a quick solution, developers can add this to a mu-plugin checking if the request is a WPGraphQL request. This solution should be removed once we have found a better approach. 

```php
// Adjust endpoint as needed.
$is_graphql = strpos($_SERVER['REQUEST_URI'], '/graphql') !== FALSE;
if ($is_graphql) {
  add_filter('override_load_textdomain',
    function ($override, $domain, $mofile) {
      return $domain === 'wp-graphql';
    }, 10, 3);
}
```

A testing branch has been created by another collaborator with the same issue: https://github.com/wp-graphql/wp-graphql/issues/1873#issuecomment-1401477766 @idflood

<img width="525" alt="image" src="https://user-images.githubusercontent.com/18492002/218270640-f8e542a4-6a5c-4384-b8f5-04764093b993.png">

<img width="931" alt="image" src="https://user-images.githubusercontent.com/18492002/218270651-6593427b-2273-448c-a9ca-fc7965cbe1d2.png">

### WPGraphQL Version

1.13.8

### WordPress Version

6.1.1

### PHP Version

8.0.27

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes

**Comment by jasonbahl** [comment]
> Additionally, the whole schema seems to be created and queried during each request, generating a massive object that is impossible to cache.

@creative-andrew I don't believe this is the case.

Let's take a look: 

### WordPress, no plugins

If we setup a fresh WordPress install (I'm using [localwp](https://localwp.com/) to do it) and visit the `/graphql` endpoint WordPress will do it's thing and ultimately return a 404 (because WPGraphQL is not active)

But we can use this as our baseline of WordPress execution. 

We can see that the  "apply_filters" gets called 8,246 times

![CleanShot 2023-02-14 at 17 16 12](https://user-images.githubusercontent.com/1260765/218892651-05b3b379-09cf-4a3f-8baa-869553c0d8c8.png)

And then we can dig in and see that "translate" calls it 1,954 times.

![CleanShot 2023-02-14 at 17 18 04](https://user-images.githubusercontent.com/1260765/218892890-d19f771b-1d29-4975-bfb0-bcdf6b791208.png)

If we visit the `/wp-json/wp/v2/posts` endpoint, we will see similar information. 

"apply_filters" is called 8,887 times for this REST endpoint, and "translate" is called 4,110 times.

![CleanShot 2023-02-14 at 17 19 29](https://user-images.githubusercontent.com/1260765/218893005-e3b8602a-e938-4a93-853d-a8e18a4c1c02.png)

If we visit the `/wp-json/wp/v2` endpoint, we see the following: 

"apply_filters" is called 17,108 times for this REST endpoint, and "translate" is called 8,218 times.

![CleanShot 2023-02-14 at 17 34 23](https://user-images.githubusercontent.com/1260765/218894855-4a27bab8-dcdf-4047-9c34-80c0d53e7ccc.png)


### WPGraphQL Active

If we activate WPGraphQL (v1.13.8) and visit the `/graphl` endpoint, this time we don't get the 404, instead we get the WPGraphQL error message saying we need to pass a query. 

![CleanShot 2023-02-14 at 17 21 32](https://user-images.githubusercontent.com/1260765/218893365-aee4af08-92d7-420f-8a49-48e2cf39d119.png)

If we look at the profiling for this request, we'll see the following: 

![CleanShot 2023-02-14 at 17 27 49](https://user-images.githubusercontent.com/1260765/218894016-96c75ef1-0c77-4de8-8f37-9238cd168703.png)

apply_filters called `13,401` times, `9,654` of them from `translate`.

If we go back to WPGraphQL v1.6.5 (shortly after the 1.6 release that targeted the "lazy loading" problem) we would see the following output:

apply_filters called `12,817` times, `9,306` of them from `translate`.

So yes, a there's an increase from some of the other endpoints, but definitely not the whole schema worth.

![CleanShot 2023-02-14 at 17 27 40](https://user-images.githubusercontent.com/1260765/218894028-cd2ed123-e04c-4b8b-9c21-b3aae5fe7afb.png)

If we go back to WPGraphQL v1.5.9, before the v1.6.0 release, we will see a significant change in the profiling, just by visiting the `graphql` endpoint and not even executing a query:

![CleanShot 2023-02-14 at 17 27 11](https://user-images.githubusercontent.com/1260765/218894037-e9b0cf89-c29f-4089-84d5-d1fdc1980586.png)

Here we see `apply_filters` called 21,112 times, (increase from 12,817 in v1.6.5)
`strtolower` called 12,811 times (increase from 1,192 in v1.6.5)
WPGraphQL\Registry\TypeRegistry->format_key called 10,011 times, (increase from 898 in v1.6.5)
preg_match called 8,389 times (increase from 1,834 in v1.6.5)

-----

I definitely think we have _something_ to address here, but I don't think we have a regression to the 1.6 release. I don't see evidence suggesting that "the whole schema seems to be created and queried during each request". 

This would be true for Introspection Queries, but I don't believe it's the case for every query. 

Now, when queries are executed, the Types required to fulfill them will be loaded, so that would have an increase as well, but definitely not to the scope of loading the whole schema for each request. 

So, the more complex queries get, the more types will be loaded, so I would expect an increase in Types being loaded for more complex queries. 

----

I think we definitely should look into how we can register Types/Fields so that the descriptions are only executed/translated when needed (i.e. in Introspection Queries), but again, I don't believe there's evidence of a regression to 1.6 where the entire Schema is being loaded.

**Comment by justlevine** [comment]
(related: [caching get_schema() thread on slack](https://wp-graphql.slack.com/archives/C3NM1M291/p1676113374565389?thread_ts=1676113374.565389&cid=C3NM1M291) )

**Comment by justlevine** [comment]
From core: https://make.wordpress.org/core/2023/07/24/i18n-performance-analysis/ 

Seems like adopting lazy-loading is the way to go, while still benefiting from any upstream improvements to the parser.

**Comment by justlevine** [comment]
I know that @jasonbahl has started moving to implement interfaces for _everything_ in #3356 , but I do want to refresh this so we have an actual benchmark to test and close.

Everything that follows is me paraphrasing/selective quoting the findings from my friend and colleague @aryanjasala when testing with WPGraphQL Content Blocks*:

(*since it's important to see how a "core" issue can balloon outside of the core plugin).

---

> We observed over 2,500 calls to `__()` (`translate()`) on a standard content query from GraphQL — even when no translation was required and only a single block was present on the page.

> We saw ~1,280 unique __() calls from the wp-graphql text domain, even on:
>
> - Empty pages
> - Pages with a few blocks
> - Pages using patterns

### Stack Trace

![Image](https://github.com/user-attachments/assets/4240af86-b706-4e1a-be63-1b9154fa0e5d)

```log
  #0 /app/public/wp-includes/class-wp-hook.php(324): WPGraphQL\Utils\InstrumentSchema::check_field_permissions
#1 /app/public/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters
#2 /app/public/wp-includes/plugin.php(517): WP_Hook->do_action
#3 /app/public/wp-content/plugins/wp-graphql/src/Utils/InstrumentSchema.php(115): do_action
#4 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(766): WPGraphQL\Utils\InstrumentSchema::WPGraphQL\Utils\{closure}
#5 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(674): GraphQL\Executor\ReferenceExecutor->resolveFieldValueOrError
#6 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1391): GraphQL\Executor\ReferenceExecutor->resolveField
#7 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1330): GraphQL\Executor\ReferenceExecutor->executeFields
#8 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1281): GraphQL\Executor\ReferenceExecutor->collectAndExecuteSubfields
#9 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1140): GraphQL\Executor\ReferenceExecutor->completeObjectValue
#10 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(946): GraphQL\Executor\ReferenceExecutor->completeAbstractValue
#11 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(806): GraphQL\Executor\ReferenceExecutor->completeValue
#12 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1048): GraphQL\Executor\ReferenceExecutor->completeValueCatchingError
#13 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(929): GraphQL\Executor\ReferenceExecutor->completeListValue
#14 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(806): GraphQL\Executor\ReferenceExecutor->completeValue
#15 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(684): GraphQL\Executor\ReferenceExecutor->completeValueCatchingError
#16 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1391): GraphQL\Executor\ReferenceExecutor->resolveField
#17 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1330): GraphQL\Executor\ReferenceExecutor->executeFields
#18 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1281): GraphQL\Executor\ReferenceExecutor->collectAndExecuteSubfields
#19 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(951): GraphQL\Executor\ReferenceExecutor->completeObjectValue
#20 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(806): GraphQL\Executor\ReferenceExecutor->completeValue
#21 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(684): GraphQL\Executor\ReferenceExecutor->completeValueCatchingError
#22 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1391): GraphQL\Executor\ReferenceExecutor->resolveField
#23 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(319): GraphQL\Executor\ReferenceExecutor->executeFields
#24 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(258): GraphQL\Executor\ReferenceExecutor->executeOperation
#25 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/Executor.php(184): GraphQL\Executor\ReferenceExecutor->doExecute
#26 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/GraphQL.php(163): GraphQL\Executor\Executor::promiseToExecute
#27 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Server/Helper.php(293): GraphQL\GraphQL::promiseToExecute
#28 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Server/Helper.php(201): GraphQL\Server\Helper->promiseToExecuteOperation
#29 /app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Server/StandardServer.php(119): GraphQL\Server\Helper->executeOperation
#30 /app/public/wp-content/plugins/wp-graphql/src/Request.php(706): GraphQL\Server\StandardServer->executeRequest
#31 /app/public/wp-content/plugins/wp-graphql/src/Router.php(473): WPGraphQL\Request->execute_http
#32 /app/public/wp-content/plugins/wp-graphql/src/Router.php(257): WPGraphQL\Router::process_http_request
#33 /app/public/wp-includes/class-wp-hook.php(324): WPGraphQL\Router::resolve_http_request
#34 /app/public/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters
#35 /app/public/wp-includes/plugin.php(565): WP_Hook->do_action
#36 /app/public/wp-includes/class-wp.php(418): do_action_ref_array
#37 /app/public/wp-includes/class-wp.php(813): WP->parse_request
#38 /app/public/wp-includes/functions.php(1336): WP->main
#39 /app/public/wp-blog-header.php(16): wp
#40 /app/public/index.php(17): require
```

#L31 (`WPGraphQL\Request::execute_http()`) is when the schema construction begins leading to `$graphql_config['description'] = __( '...', 'wp-graphql' );` to be evaluated.

### Env

```log
WPGraphQL - 2.1.1
WPGraphQL Content Blocks - 4.8.2
WordPress Core - 6.7.2
WP_ENVIRONMENT_TYPE - production
PHP - 8.2.27
Setup - LocalWP + XHProf + XHGUI
```
Enabling XHPROF for WP (assuming installed + enabled via php.ini):
```php
// Enable XHProf
if ( extension_loaded( 'xhprof' ) ) {
    require_once ABSPATH . 'xhprof/xhprof_lib/utils/xhprof_lib.php';
    require_once ABSPATH . 'xhprof/xhprof_lib/utils/xhprof_runs.php';
    xhprof_enable( XHPROF_FLAGS_CPU | XHPROF_FLAGS_MEMORY );

    register_shutdown_function( function() {
        $xhprof_data = xhprof_disable();
        $xhprof_runs = new XHProfRuns_Default( ABSPATH . 'xhprof_data' ); // specify where to store the profiling files
        $run_id = $xhprof_runs->save_run( $xhprof_data, 'snapwp' );
        error_log( 'XHProf run saved: ' . $run_id );
    });
}
```
(More info on XHProf: https://make.wordpress.org/performance/handbook/measuring-performance/profiling-php-performance-with-xhprof/) 

---

Recommendation is unchanged: make `$config['description']` to be type `string | callable():string`.

This is an opt-in change (which we can hint-to with debug messages) for plugin developers), but it's nonbreaking and can be done independently of any other resolver work happening in #3356 or elsewhere.

**Comment by jasonbahl** [comment]
@justlevine I have descriptions as a callable in progress as well.

so we will be able to pass fields as a callable as well as pass description of types and fields as a callable and I'm seeing promising improvements to the number of times gettext is called

**Comment by jasonbahl** [comment]
For anyone following this issue, we have a [PR](https://github.com/wp-graphql/wp-graphql/pull/3356) that allows for fields and descriptions to be defined as callables instead of being defined statically within the arrays passed to `register_graphql_*` functions.

Promising results from my testing: https://github.com/wp-graphql/wp-graphql/pull/3356#issuecomment-2808174051 and https://github.com/wp-graphql/wp-graphql/pull/3356#issuecomment-2810162136

Would love to see if anyone has had a chance to test in their environment and report back.

**Comment by aryanjasala** [comment]
### Performance Benchmark Comparison After Bug Fix

@jasonbahl @justlevine Following the recent update, here's the benchmark testing for a page with a single paragraph block.


| **Plugin Version** | **Translate Calls**<br>*(wp-graphql text domain)* | **Self Wall Time**<br>*(__() function)* | **Memory Usage**<br>*(__() function)* | **Self CPU Time**<br>*(__() function)* |
|--------------------|---------------------------------------------------|---------------------------------------|--------------------------------------|--------------------------------------|
| **2.1.1**          | 4,613                                             | 11,920 µs                             | 138,056 bytes                        | 12,851 µs                            |
| **2.3.0**          | 369                                               | 6,056 µs                              | 67,384 bytes                         | 6,676 µs                             |
| **Improvement**    | **−92.0%**                                        | **−49.2%**                            | **−51.2%**                           | **−48.0%**                           |


**These results demonstrate that the fix significantly improved translation call handling and core function performance in `wp-graphql`**

**Comment by justlevine** [comment]
Next step is docs + and helping pushing ecosystem adoption.
I think that work can/should continue as part of #3354 , and we can close _this_ issue as fixed.
