### ISSUE TITLE
Local testing with "composer run-test" fails with error "...function "graphql_activation_callback" not found..."

### ISSUE THREAD

**Issue by missionmike** [wp-graphql/wp-graphql#2743]
### Description

While following the steps located in the docs: https://www.wpgraphql.com/docs/testing#testing-with-docker

The `composer run-test` step fails with:

`PHP Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "graphql_activation_callback" not found or invalid function name in /var/www/html/wp-includes/class-wp-hook.php:308`

**Expected results:** run the test suite and pass with flying colors 🥳

### Steps to reproduce

1. Clone repository without making any changes.
2. Run `composer build-test`
3. Run `composer run-test`

### Additional context

<details>
  <summary>Full Terminal Output</summary>

```
wp-graphql on  develop via  desktop-linux is  v1.12.0 via  v17.9.1 via  v8.1.9 took 41s 
❯ composer run-test  
> bash bin/run-docker.sh run '-t'
Creating wp-graphql_testing_run ... done
WordPress: 6.1 PHP: 8.1
Moving to WordPress root directory /var/www/html.
WordPress not found in /var/www/html - copying now...
Complete! WordPress has been successfully copied to /var/www/html
No 'wp-config.php' found in /var/www/html, but 'WORDPRESS_...' variables supplied; copying 'wp-config-docker.php' (WORDPRESS_DB_HOST WORDPRESS_DB_NAME WORDPRESS_DB_PASSWORD WORDPRESS_DB_USER)
2023/03/02 03:49:44 Waiting for: tcp://app_db:3306
2023/03/02 03:49:44 Connected to tcp://app_db:3306
Success: Added the constant 'WP_AUTO_UPDATE_CORE' to the 'wp-config.php' file with the value 'false'.
Success: Added the constant 'AUTOMATIC_UPDATER_DISABLED' to the 'wp-config.php' file with the value 'true'.
Success: Value passed for 'SITEURL' option is unchanged.
Success: Value passed for 'HOME' option is unchanged.
Running WordPress version: 6.1.1 at http://localhost
[02-Mar-2023 03:49:46 UTC] PHP Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "graphql_activation_callback" not found or invalid function name in /var/www/html/wp-includes/class-wp-hook.php:308
Stack trace:
#0 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#1 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#2 /var/www/html/wp-admin/includes/plugin.php(691): do_action('activate_wp-gra...', NULL)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php(347): activate_plugin('wp-graphql/wp-g...', '', NULL)
#4 [internal function]: Plugin_Command->activate(Array, Array)
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func(Array, Array, Array)
#6 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(491): call_user_func(Object(Closure), Array, Array)
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(419): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(442): WP_CLI\Runner->run_command(Array, Array)
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1256): WP_CLI\Runner->run_command_and_exit()
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#14 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#15 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#16 {main}
  thrown in /var/www/html/wp-includes/class-wp-hook.php on line 308
Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "graphql_activation_callback" not found or invalid function name in /var/www/html/wp-includes/class-wp-hook.php:308
Stack trace:
#0 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#1 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#2 /var/www/html/wp-admin/includes/plugin.php(691): do_action('activate_wp-gra...', NULL)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php(347): activate_plugin('wp-graphql/wp-g...', '', NULL)
#4 [internal function]: Plugin_Command->activate(Array, Array)
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func(Array, Array, Array)
#6 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(491): call_user_func(Object(Closure), Array, Array)
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(419): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(442): WP_CLI\Runner->run_command(Array, Array)
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1256): WP_CLI\Runner->run_command_and_exit()
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#14 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#15 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#16 {main}
  thrown in /var/www/html/wp-includes/class-wp-hook.php on line 308
ERROR: 255
Script bash bin/run-docker.sh run handling the docker-run event returned with error code 255
Script @docker-run -t was called via run-test
```
</details>

### WPGraphQL Version

1.13.9

### WordPress Version

6.1

### PHP Version

8.1

### Additional enviornment details

Mac OS Monterey 12.6, attempting to run tests via terminal within VS Code. Same error occurs in terminal outside VS Code.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Did you make sure to run `composer install` before trying to build the docker image? When you download the repo directly from GitHub you need to install the dependencies (which generates the autoloader that includes the `activation.php` file)

**Comment by missionmike** [comment]
> Did you make sure to run `composer install` before trying to build the docker image? When you download the repo directly from GitHub you need to install the dependencies (which generates the autoloader that includes the `activation.php` file)

Oh no 🤦‍♂️

I was mistakenly under the impression that the docker build process was running the `composer install` under the hood. I don't know _why_ I was under that impression, but it was my misunderstaning!

Running `composer install` first definitely fixes the issue for me 😅

If anyone ever Googles this error like I did, perhaps they'll find this issue and be able to move past it quickly.

Thank you!
