### ISSUE TITLE
Error: DiscussionSettings fields must be an object with field names as keys or a function which returns such an object.

### ISSUE THREAD

**Issue by brandontruong** [wp-graphql/wp-graphql#368]
Hi there,

I am getting above error after installing successfully wp-graphql plug in. Do you have any ideas of why I am getting that error?

Thanks

**Comment by jasonbahl** [comment]
@brandontruong I need more info to help. Where are you getting the error? Just on Certain GraphQL requests? All requests? The more context and info you can provide the better. 

do you have any plugins or themes that use “register_setting” in any way, specifically to add “discussion” settings?

**Comment by brandontruong** [comment]
Hi @jasonbahl ,
I have disabled all the plugins except WP Grapghql. 
In term of theme, I have used one of the default themes from Wordpress which is Twenty Seventeen.
I am not really sure what you mean by 'do you have any plugins or themes that use “register_setting” in any way, specifically to add “discussion” settings?'

So basically, when I use ChromeiQL to access my website endpoint which is http://brandontruong.me/graphql

I got the error below. Are they enough details for you? Sorry if I dont explain well enough. I am pretty new with this.

Error: DiscussionSettings fields must be an object with field names as keys or a function which returns such an object.
    at invariant (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/dist/chromeiql.js:14605:11)
    at defineFieldMap (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/dist/chromeiql.js:13748:54)
    at GraphQLObjectType.getFields (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/dist/chromeiql.js:13705:44)
    at typeMapReducer (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/dist/chromeiql.js:16603:25)
    at chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/dist/chromeiql.js:16613:20
    at Array.forEach (<anonymous>)
    at typeMapReducer (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/dist/chromeiql.js:16604:27)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/dist/chromeiql.js:16492:34)
    at buildClientSchema (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/dist/chromeiql.js:72656:10)

**Comment by jasonbahl** [comment]
@brandontruong I'm closing this as it appears you must have figured things out. I was able to query your site using GraphiQL today. 

If you're still having issues, try using a different GraphiQL app as it may be an issue with ChromiQL 🤔 

<img width="1193" alt="screen shot 2018-03-31 at 12 25 55 pm" src="https://user-images.githubusercontent.com/1260765/38166284-c0937dae-34de-11e8-98df-c99f6c9ece20.png">
