### ISSUE TITLE
When defining a type during theme setup, error when referencing built-in WP_GraphQL types within it

### ISSUE THREAD

**Issue by hews** [wp-graphql/wp-graphql#390]
### What I want to do

I am trying to define my own type (below, `Subtype`) that can be nested within multiple other types.  Example schema:

```gql
Subtype {
    id
    name : string
}

ParentTypeA {
    ...
    sub : Subtype
}

ParentTypeB {
    ...
    sub : Subtype
}
```

### How I am doing it

In order to break this up in my code, I am defining `Subtype` once, and then using it in both parent types, like this:

```php
$subtype = new \WPGraphQL\Type\WPObjectType(
    [
        'name' => 'Subtype',
        'fields' => [
            'name' => [
                'type' => \WPGraphQL\Types::string(),
                'description' => 'Subtype name',
                'resolve' => function ( $indeterminate_type_of_object ) {
                    $determined_object = determine_type( $indeterminate_type_of_object );
                    return $determined_object->name;
                },
            ],
        ],
    ]
);

add_action( 'graphql_parent_type_a_fields', 'add_parent_type_a_to_graphql' );
add_action( 'graphql_parent_type_b_fields', 'add_parent_type_b_to_graphql' );

function add_fields_to_parent_type_a_in_graphql( $fields ) {
    return array_merge(
        $fields,
        [
            'sponsor' => [
                'type' => $subtype,
                'description' => 'subtype description',
                'resolve' => function ( \WP_Parent_Type_A $parent_type ) {
                    return $parent_type;
                },
            ]
        ]
    );
}

function add_fields_to_parent_type_b_in_graphql( $fields ) {
    return array_merge(
        $fields,
        [
            'sponsor' => [
                'type' => $subtype,
                'description' => 'subtype description',
                'resolve' => function ( \WP_Parent_Type_B $parent_type ) {
                    return $parent_type;
                },
            ]
        ]
    );
}
```

### What my error is

While the above is working for me just fine, the problem arose when I wanted to include a WP GraphQL-defined type (MediaItem) within my subtype:

```gql
Subtype {
    id
    name : string
    media : MediaItem
}
```

```php
$subtype = new \WPGraphQL\Type\WPObjectType(
    [
        'name' => 'Subtype',
        'fields' => [
            # ...
            'media' => [
                'type' => \WPGraphQL\Types::post_object( 'attachment' ),
                'description' => 'Subtype name',
                'resolve' => function ( $indeterminate_type_of_object ) {
                    $determined_object = determine_type( $indeterminate_type_of_object );
                    return $determined_object->media_post;
                },
            ],
        ],
    ]
);

```

Error: 

```
PHP Notice:  Undefined property: WP_Post_Type::$graphql_single_name in .../plugins/wp-graphql/src/Type/PostObject/PostObjectType.php on line 66
[Stack Trace]
PHP Notice:  Undefined property: WP_Post_Type::$graphql_single_name in .../plugins/wp-graphql/src/Type/PostObject/PostObjectType.php on line 68
[Stack Trace]
PHP Notice:  Undefined property: WP_Post_Type::$graphql_single_name in .../plugins/wp-graphql/src/Type/PostObject/PostObjectType.php on line 92
[Stack Trace]
PHP Fatal error:  Uncaught GraphQL\Error\InvariantViolation: Must be named. Unexpected name: (empty string) in /var/www/web/app/mu-plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/Utils.php:430
Stack trace:
#0 /var/www/web/app/mu-plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Definition/ObjectType.php(92): GraphQL\Utils\Utils::assertValidName('', false)
#1 /var/www/web/app/mu-plugins/wp-graphql/src/Type/WPObjectType.php(68): GraphQL\Type\Definition\ObjectType->__construct(Array)
#2 /var/www/web/app/mu-plugins/wp-graphql/src/Type/PostObject/PostObjectType.php(73): WPGraphQL\Type\WPObjectType->__construct(Array)
#3 /var/www/web/app/mu-plugins/wp-graphql/src/Types.php(424): WPGraphQL\Type\PostObject\PostObjectType->__construct('attachment')
#4 /var/www/web/app/themes/tpt-headless/inc/graphql/class-sponsor-type.php(82): WPGraphQL\Types::post_object('attachment')
#5 /var/www/web/app/themes/tpt-headless/inc/posts/class-sponsor.php(189): TPT\GraphQL\Sponsor_Type->__construct('\\TPT\\Posts\\Spon...', '\\TPT\\Posts\\Spon in /var/www/web/app/mu-plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/Utils.php on line 430
```

The error was in the assumption that when we initialize `\WPGraphQL\Types::post_object( 'attachment' )`, the objects in `$wp_post_types` have already had `$graphql_single_name` properties assigned to them via `do_graphql_request() -> \WPGraphQL::show_in_graphql()`.

*There is a workaround that fixes the error:* adding `\WPGraphQL::show_in_graphql()` to the schema definition:

```php
\WPGraphQL::show_in_graphql();
$subtype = new \WPGraphQL\Type\WPObjectType( ... );
```

---

There are essentially three possible responses here:

1. there is a right way to do what I am doing, and I am not doing it that way;
2. this is an acceptable way to do what I want, and the workaround defined above is a good way to live with it;
3.  this is a fine way to do what I want, and I shouldn't need to use a workaround, and instead we should fix the error.

**Comment by hews** [comment]
The response on Slack was:

> If you try and use classes from the plugin before the autoloader is called, they won’t exist yet. By only executing your code at `graphql_init` you ensure you’re code is executing only when the required dependencies have been setup. . .for example, if you deactivate the WPGraphQL plugin, and your custom code is tied to the graphql_init hook, it never executed, leaving the rest of your site operating fine. If you activate WPGraphQL, your code registered at graphql_init is executed and can then extend WPGraphQL. 
> 
> If you try and register types before graphql_init, you will have issues as you’re experiencing.  
> 
> It’s much like when you enqueue scripts, you do it inside `add_action( 'wp_enqueue_scripts' )`, not just somewhere random. 
>
> Using hooks properly likely reduces the risk of race conditions compared to having code executing at random times. Hooks, when used properly, ensure code is executed in specific order at specific points of the WordPress load

**Comment by hews** [comment]
So it seems that the response is: ***there is a right way to do what I am doing, and I am not doing it that way.***

The issue is best solved by defining the schema within a hook on `graphql_init`, as in:

```
$subtype = null;

add_action( 'graphql_init', 'define_subtype' );

function define_subtype() use ( $subtype ) {
    $subtype = new \WPGraphQL\Type\WPObjectType(
        [
            'name' => 'Subtype',
            'fields' => [
                'name' => [
                    'type' => \WPGraphQL\Types::string(),
                    'description' => 'Subtype name',
                    'resolve' => function ( $indeterminate_type_of_object ) {
                        $determined_object = determine_type( $indeterminate_type_of_object );
                        return $determined_object->name;
                    },
                ],
            ],
        ]
    );
}
