### ISSUE TITLE
Exception when adding the 'thumbnail' option in the 'supports' array in 'register_post_type'

### ISSUE THREAD

**Issue by rasmustaarnby** [wp-graphql/wp-graphql#475]
### Setup

Plugin version: 0.0.30

Plugins active:
- WP GraphQL
- One single file test plugin that loads on `plugins_loaded` to test custom post type registration

It's a multisite setup and plugins are activated network wide. 

### Description

Using the example from the wiki page [Extending and Customizing](https://github.com/wp-graphql/wp-graphql/wiki/Extending-and-Customizing), I'm trying to add a custom post type. 

Everything seems to work just fine when using the snippet as is. 

```
add_action( 'init', function() {
	register_post_type( 'book', [
		'label' => __( 'Books', 'wp-graphql-publishers' ),
		'supports' => [ 'title', 'editor', 'custom-fields' ],
		'public' => true,
		'show_in_graphql' => true,
		'graphql_single_name' => 'book',
		'graphql_plural_name' => 'books',
	] );
} );
```
However, when adding the `thumbnail` option to the supports array, it generates an error. 
```
add_action( 'init', function() {
	register_post_type( 'book', [
		'label' => __( 'Books', 'wp-graphql-publishers' ),
		'supports' => [ 'title', 'editor', 'custom-fields', 'thumbnail' ],
		'public' => true,
		'show_in_graphql' => true,
		'graphql_single_name' => 'book',
		'graphql_plural_name' => 'books',
	] );
} );
```

### Steps to reproduce

1) Add the following in functions.php or a single file test plugin

```
add_action( 'init', function() {
	register_post_type( 'book', [
		'label' => __( 'Books', 'wp-graphql-publishers' ),
		'supports' => [ 'title', 'editor', 'custom-fields', 'thumbnail' ],
		'public' => true,
		'show_in_graphql' => true,
		'graphql_single_name' => 'book',
		'graphql_plural_name' => 'books',
	] );
} );
```
2) Run the cli command `wp graphql generate-static-schema` to test and generate schema.

### Stack trace
```
PHP Notice:  Undefined property: WP_Post_Type::$graphql_single_name in /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/src/Type/PostObject/PostObjectType.php on line 66
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/wp:0
PHP   2. include() /usr/local/bin/wp:4
PHP   3. include() phar:///usr/local/bin/wp/php/boot-phar.php:8
PHP   4. WP_CLI\bootstrap() phar:///usr/local/bin/wp/php/wp-cli.php:23
PHP   5. WP_CLI\Bootstrap\LaunchRunner->process() phar:///usr/local/bin/wp/php/bootstrap.php:75
PHP   6. WP_CLI\Runner->start() phar:///usr/local/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php:23
PHP   7. WP_CLI\Runner->_run_command_and_exit() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:1109
PHP   8. WP_CLI\Runner->run_command() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:383
PHP   9. WP_CLI\Dispatcher\Subcommand->invoke() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:360
PHP  10. call_user_func:{phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:425}() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:425
PHP  11. WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:425
PHP  12. call_user_func:{phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:89}() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:89
PHP  13. WPGraphQL_CLI_Command->generate_static_schema() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:89
PHP  14. WPGraphQL::get_schema() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/cli/wp-cli.php:36
PHP  15. WPGraphQL\WPSchema->__construct() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/wp-graphql.php:480
PHP  16. WPGraphQL\WPSchema->__construct() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/src/WPSchema.php:46
PHP  17. WPGraphQL\WPSchema->getTypeMap() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Schema.php:137
PHP  18. WPGraphQL\WPSchema->collectAllTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Schema.php:195
PHP  19. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Schema.php:223
PHP  20. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:134
PHP  21. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:134
PHP  22. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:134
PHP  23. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:134
PHP  24. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:134
PHP  25. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:95
PHP  26. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:134
PHP  27. WPGraphQL\Type\PostObject\PostObjectType->getFields() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:125
PHP  28. GraphQL\Type\Definition\FieldDefinition::defineFieldMap() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Definition/ObjectType.php:127
PHP  29. WPGraphQL\Type\PostObject\PostObjectType::WPGraphQL\Type\PostObject\{closure}() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Definition/FieldDefinition.php:97
PHP  30. WPGraphQL\Types::post_object() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/src/Type/PostObject/PostObjectType.php:541
PHP  31. WPGraphQL\Type\PostObject\PostObjectType->__construct() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/src/Types.php:485
PHP Notice:  Undefined property: WP_Post_Type::$graphql_single_name in /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/src/Type/PostObject/PostObjectType.php on line 68
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/wp:0
PHP   2. include() /usr/local/bin/wp:4
PHP   3. include() phar:///usr/local/bin/wp/php/boot-phar.php:8
PHP   4. WP_CLI\bootstrap() phar:///usr/local/bin/wp/php/wp-cli.php:23
PHP   5. WP_CLI\Bootstrap\LaunchRunner->process() phar:///usr/local/bin/wp/php/bootstrap.php:75
PHP   6. WP_CLI\Runner->start() phar:///usr/local/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php:23
PHP   7. WP_CLI\Runner->_run_command_and_exit() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:1109
PHP   8. WP_CLI\Runner->run_command() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:383
PHP   9. WP_CLI\Dispatcher\Subcommand->invoke() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:360
PHP  10. call_user_func:{phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:425}() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:425
PHP  11. WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:425
PHP  12. call_user_func:{phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:89}() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:89
PHP  13. WPGraphQL_CLI_Command->generate_static_schema() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:89
PHP  14. WPGraphQL::get_schema() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/cli/wp-cli.php:36
PHP  15. WPGraphQL\WPSchema->__construct() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/wp-graphql.php:480
PHP  16. WPGraphQL\WPSchema->__construct() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/src/WPSchema.php:46
PHP  17. WPGraphQL\WPSchema->getTypeMap() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Schema.php:137
PHP  18. WPGraphQL\WPSchema->collectAllTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Schema.php:195
PHP  19. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Schema.php:223
PHP  20. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:134
PHP  21. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:134
PHP  22. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:134
PHP  23. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:134
PHP  24. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:134
PHP  25. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:95
PHP  26. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:134
PHP  27. WPGraphQL\Type\PostObject\PostObjectType->getFields() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:125
PHP  28. GraphQL\Type\Definition\FieldDefinition::defineFieldMap() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Definition/ObjectType.php:127
PHP  29. WPGraphQL\Type\PostObject\PostObjectType::WPGraphQL\Type\PostObject\{closure}() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Definition/FieldDefinition.php:97
PHP  30. WPGraphQL\Types::post_object() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/src/Type/PostObject/PostObjectType.php:541
PHP  31. WPGraphQL\Type\PostObject\PostObjectType->__construct() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/src/Types.php:485
PHP Notice:  Undefined property: WP_Post_Type::$graphql_single_name in /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/src/Type/PostObject/PostObjectType.php on line 92
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/wp:0
PHP   2. include() /usr/local/bin/wp:4
PHP   3. include() phar:///usr/local/bin/wp/php/boot-phar.php:8
PHP   4. WP_CLI\bootstrap() phar:///usr/local/bin/wp/php/wp-cli.php:23
PHP   5. WP_CLI\Bootstrap\LaunchRunner->process() phar:///usr/local/bin/wp/php/bootstrap.php:75
PHP   6. WP_CLI\Runner->start() phar:///usr/local/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php:23
PHP   7. WP_CLI\Runner->_run_command_and_exit() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:1109
PHP   8. WP_CLI\Runner->run_command() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:383
PHP   9. WP_CLI\Dispatcher\Subcommand->invoke() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:360
PHP  10. call_user_func:{phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:425}() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:425
PHP  11. WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:425
PHP  12. call_user_func:{phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:89}() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:89
PHP  13. WPGraphQL_CLI_Command->generate_static_schema() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:89
PHP  14. WPGraphQL::get_schema() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/cli/wp-cli.php:36
PHP  15. WPGraphQL\WPSchema->__construct() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/wp-graphql.php:480
PHP  16. WPGraphQL\WPSchema->__construct() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/src/WPSchema.php:46
PHP  17. WPGraphQL\WPSchema->getTypeMap() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Schema.php:137
PHP  18. WPGraphQL\WPSchema->collectAllTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Schema.php:195
PHP  19. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Schema.php:223
PHP  20. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:134
PHP  21. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:134
PHP  22. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:134
PHP  23. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:134
PHP  24. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:134
PHP  25. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:95
PHP  26. GraphQL\Utils\TypeInfo::extractTypes() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:134
PHP  27. WPGraphQL\Type\PostObject\PostObjectType->getFields() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:125
PHP  28. GraphQL\Type\Definition\FieldDefinition::defineFieldMap() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Definition/ObjectType.php:127
PHP  29. WPGraphQL\Type\PostObject\PostObjectType::WPGraphQL\Type\PostObject\{closure}() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Definition/FieldDefinition.php:97
PHP  30. WPGraphQL\Types::post_object() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/src/Type/PostObject/PostObjectType.php:541
PHP  31. WPGraphQL\Type\PostObject\PostObjectType->__construct() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/src/Types.php:485
PHP  32. WPGraphQL\Type\PostObject\PostObjectType::fields() /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/src/Type/PostObject/PostObjectType.php:69
PHP Fatal error:  Uncaught GraphQL\Error\InvariantViolation: Must be named. Unexpected name: (empty string) in /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/Utils.php:430
Stack trace:
#0 /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Definition/ObjectType.php(92): GraphQL\Utils\Utils::assertValidName('', false)
#1 /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/src/Type/WPObjectType.php(63): GraphQL\Type\Definition\ObjectType->__construct(Array)
#2 /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/src/Type/PostObject/PostObjectType.php(73): WPGraphQL\Type\WPObjectType->__construct(Array)
#3 /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/src/Types.php(485): WPGraphQL\Type\PostObject\PostObjectType->__construct('attachment')
#4 /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/src/Type/PostObject/PostObjectType.php(541): WPGraphQL\Types::post_object('attachment')
#5 /host/ww in /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/Utils.php on line 430
Getting the Schema...
```

### Possibly related issues

#11 
#173 
#146 
#243 

### Update: Work around

Adding the following snippet resolves the above issue but I doubt that it is the correct solution. 

```
add_filter( 'register_post_type_args', 'set_attachment_args', 5, 2 );
	
function set_attachment_args( $args, $object_name ) {
	if ( $object_name == 'attachment' ) {
		$args['show_in_graphql']     = true;
		$args['graphql_single_name'] = 'attachment';
		$args['graphql_plural_name'] = 'attachments';
	}

	return $args;
}
```

**Comment by jasonbahl** [comment]
@rasmustaarnby thanks for the detailed issue. we'll check it out. Of course, PRs welcome if you get to the root of the issue as well 😄

**Comment by rasmustaarnby** [comment]
@jasonbahl Sure. Right now I'm going with the work around as I need to get it done for a client but I'll give it a look.

**Comment by jasonbahl** [comment]
@rasmustaarnby are you only noticing issues with the static Schema generation or are you also noticing issues trying to execute queries, etc?

**Comment by rasmustaarnby** [comment]
@jasonbahl I couldn't get the graphQL IDE to return a post type and a meta field, which I new was added in the exact same way as another one, so I startet to look around because I thought it could be a cache issue. Hence, I ended up testing using the static schema generator which gave me the above error. I'll double check things but I'm pretty sure the error is also there when querying because it wont return the custom post type no matter what. I can try to remove 'thumbnail' from the supports array in custom post type I'm adding.

**Comment by rasmustaarnby** [comment]
And there graphQL IDE is returning nicely now too, after I added the work around.

**Comment by rasmustaarnby** [comment]
Alright did some digging. 

The issue originates from https://github.com/wp-graphql/wp-graphql/blob/release/v0.0.30/src/Type/PostObject/PostObjectType.php#L539-L549 where the it checks for `post_type_supports( $post_type_object->name, 'thumbnail' )` and subsequently calls `Types::post_object( 'attachment' )`. 

Following the trial it calls [`new PostObjectType( $post_type )`](https://github.com/wp-graphql/wp-graphql/blob/develop/src/Types.php#L485), at this point $post_type is set to "attachment". 
This results in it trying to set config name with [`self::$post_type_object->graphql_single_name`](https://github.com/wp-graphql/wp-graphql/blob/release/v0.0.30/src/Type/PostObject/PostObjectType.php#L66) which leads to the exception 

```
PHP Fatal error:  Uncaught GraphQL\Error\InvariantViolation: Must be named. Unexpected name: (empty string) in /host/www/fagligsenior/frontend/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/Utils.php:430
```
I haven't found the solution yet but my guess is it resolves to the order of events or the global `$wp_post_types` being overridden without the values from [here](https://github.com/wp-graphql/wp-graphql/blob/release/v0.0.30/wp-graphql.php#L322-L326) perhaps. 

I'll keep looking but it's the first time using the plugin so still discovering how everything is set up.

**Comment by jasonbahl** [comment]
Thanks for the info. This is super helpful for troubleshooting!

**Comment by rasmustaarnby** [comment]
Sure, it's a great plugin and I'd like to do what I can to contribute. We're already making a switch from the WP REST api to this.

Poked around a bit more and I almost certain the issue is related to your settings from the method [show_in_graphql](https://github.com/wp-graphql/wp-graphql/blob/release/v0.0.30/wp-graphql.php#L317) is being overridden later on. 

According to the codex register post types should not be done before the init hook. As far as I can see you're initialising everything on `after_setup_theme`, which I assume is before `global $wp_post_types` is set up properly. 

I tried moving the `show_in_graphql` method to the `init` hook and that solved the issue. 

However, if the above is correct then I think a more appropriate solution would be to rewrite the `show_in_graphql` method to use the `register_post_type_args` filter to modify the post args, instead of altering the global var directly.

**Comment by rasmustaarnby** [comment]
@jasonbahl Great work :thumbsup: I forked the repo but you beat me to it. I'll make sure to pull and test when I'm back at the office tomorrow.
